"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createContext } from "react";

export const useSemester=createContext();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Navokta Notes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [semester, setSemester] = useState(null);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <useSemester.Provider value={{semester,setSemester}}>
        {children}
        </useSemester.Provider>
      </body> 
    </html>
  );
}
